version: 2
 
jobs:
    build:
        working_directory: ~/circleci-python
        docker:
            - image: circleci/python:3.6.4
        steps:
            - checkout
            # - run:
                # name: Set AWS region
                # command: aws configure set region ap-northeast-1d
            - run:
                name: build
                command: pwd
                # command: pwd && git config --global user.name "katakatana" && git config --global user.email "tbol42356@gmail.com"
                # command: aws deploy create-deployment --application-name appA-name --deployment-group-name appA-deploy-group --github-location repository="your/repository",commitId="$CIRCLE_SHA1"
    # EC2 に SSH 接続・デプロイを実行
    deploy:
        working_directory: ~/circleci-python
        docker:
            - image: circleci/python:3.6.4
            # image: circleci/classic:edge
        steps:
            - checkout
            # CircleCI に登録した秘密鍵を呼び出す
            # - add_ssh_keys:
            # CircleCI に登録した環境変数を使って SSH
            # - run: ssh ${USER_NAME}@${HOST_NAME}
            - run: python3 -m venv dnsenv
            - run: source dnsenv/bin/activate
            - run: pwd
            - run: who
            - run: pip install --upgrade pip
            - run: pip3 install octodns
            - run: pip3 install boto3
            - run: export AWS_ACCESS_KEY_ID='AKIAYEPGHXDNDAXIYMAS'
            - run: export AWS_SECRET_ACCESS_KEY='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'
            # - run: git --version && printenv
            # - run: git colne https://github.com/katakakana/dns.git
            - run: octodns-validate --config-file ./octoDNS/production.yaml
            - run: octodns-sync --config-file=./octoDNS/production.yaml
            - run: octodns-sync --config-file=./octoDNS/production.yaml --doit

workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build
            - deploy:
                requires:
                    # build ジョブに依存してるので、先に build ジョブを実行しろ！
                    - build
                # master ブランチに push された場合のみ deploy
                filters:
                    branches:
                        only: master
