version: 2

jobs:
    # EC2 に SSH 接続・デプロイを実行
    dns_change:
        working_directory: ~/circleci-python
        docker:
            - image: circleci/python:3.6.4
        steps:
            - checkout
            - run: printenv
            - run:
                  name: python3 build
                  command: |-
                     pwd
                     python3 -m venv dnsenv
                     source dnsenv/bin/activate
                     sudo pip install --upgrade pip
            - run:
                  name: octoDNS build
                  command: |-
                     sudo pip3 install octodns
                     sudo pip3 install boto3

            - run:
                  name: octoDNS run
                  command: |-
                     octodns-validate --config-file ./octoDNS/production.yaml
                     octodns-sync --config-file=./octoDNS/production.yaml
                     octodns-sync --config-file=./octoDNS/production.yaml --doit

workflows:
    version: 2
    dns_change:
        jobs:
            - dns_change:
                  context: AWS
                  filters:
                      branches:
                          only: master
