version: 2
 
jobs:
    build:
        docker:
            - image: cdssnc/aws-cli
        steps:
            - checkout
            # - run:
                # name: Set AWS region
                # command: aws configure set region ap-northeast-1d
            - run:
                name: Deploy
                command: cd ./
                # command: aws deploy create-deployment --application-name appA-name --deployment-group-name appA-deploy-group --github-location repository="your/repository",commitId="$CIRCLE_SHA1"
    # EC2 に SSH 接続・デプロイを実行
    deploy:
        machine:
            image: circleci/classic:edge
        steps:
            - checkout
            # CircleCI に登録した秘密鍵を呼び出す
            # - add_ssh_keys:
            # CircleCI に登録した環境変数を使って SSH
            # - run: ssh ${USER_NAME}@${HOST_NAME}
            - run: git --version && printenv
 
workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build
            - deploy:
                requires:
                    # build ジョブに依存してるので、先に build ジョブを実行しろ！
                    - build
                # master ブランチに push された場合のみ deploy
                filters:
                    branches:
                        only: master
