manager:
  max_workers: 2

providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./dns/octoDNS/config
    default_ttl: 3600
    enforce_order: True
  route53:
    class: octodns.provider.route53.Route53Provider
    access_key_id: env/AWS_ACCESS_KEY_ID
    secret_access_key: env/AWS_SECRET_ACCESS_KEY
zones:
  katakana.com.:
    sources:
      # - ../output/route53.test.yaml
      - config 
    targets:
      - route53
